version: "3"
services:
  node:
    image: "alpha:latest"
    ports:
      - "4000:8080"
    networks:
      - webnet
  db:
    image: "postgres:11"
    ports:
      - "54320:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  dbdata:
